name: ci-deploy
on: [push]
jobs:
  docker-config:
    runs-on: ubuntu-latest
    steps:
      - name: set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: set up DOCKER BUILDX
        uses: docker/setup-buildx-action@v3
      - name: Login to DOCKER HUB
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: BUILD and PUSH
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: alexroza/bot-scythe-marie-curie:latest
          build-args: DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
  deploy-aws:
    runs-on: ubuntu-latest
    needs: docker-config
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: terraform setup
        uses: hashicorp/setup-terraform@v3

        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: terraform init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
