name: ci-build-push-docker-image
on: [push]
jobs:
  docker-config:
    runs-on: ubuntu-latest
    steps:
      - name: set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: set up DOCKER BUILDX
        uses: docker/setup-buildx-action@v3
      - name: Login to DOCKER HUB
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: BUILD and PUSH
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: alexroza/bot-scythe-marie-curie:latest
          build-args: DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
